const oxlintRules = new Set(
  new Set([
    'react/button-has-type',
    'react/checked-requires-onchange-or-readonly',
    'react/display-name',
    'react-hooks/exhaustive-deps',
    'react/forbid-component-props',
    'react/forbid-dom-props',
    'react/forbid-elements',
    'react/forward-ref-uses-ref',
    'react/hook-use-state',
    'react/iframe-missing-sandbox',
    'react/jsx-boolean-value',
    'react/jsx-curly-brace-presence',
    'react/jsx-filename-extension',
    'react/jsx-fragments',
    'react/jsx-handler-names',
    'react/jsx-key',
    'react/jsx-max-depth',
    'react/jsx-no-comment-textnodes',
    'react/jsx-no-constructed-context-values',
    'react/jsx-no-duplicate-props',
    'react/jsx-no-script-url',
    'react/jsx-no-target-blank',
    'react/jsx-no-undef',
    'react/jsx-no-useless-fragment',
    'react/jsx-pascal-case',
    'react/jsx-props-no-spread-multi',
    'react/jsx-props-no-spreading',
    'react/no-array-index-key',
    'react/no-children-prop',
    'react/no-clone-element',
    'react/no-danger',
    'react/no-danger-with-children',
    'react/no-did-mount-set-state',
    'react/no-did-update-set-state',
    'react/no-direct-mutation-state',
    'react/no-find-dom-node',
    'react/no-is-mounted',
    'react/no-multi-comp',
    'react/no-namespace',
    'react/no-object-type-as-default-prop',
    'react/no-react-children',
    'react/no-redundant-should-component-update',
    'react/no-render-return-value',
    'react/no-set-state',
    'react/no-string-refs',
    'react/no-this-in-sfc',
    'react/no-unescaped-entities',
    'react/no-unknown-property',
    'react/no-unsafe',
    'react/no-unstable-nested-components',
    'react/no-will-update-set-state',
    'react/only-export-components',
    'react/prefer-es6-class',
    'react/prefer-function-component',
    'react/react-in-jsx-scope',
    'react-hooks/rules-of-hooks',
    'react/self-closing-comp',
    'react/state-in-constructor',
    'react/style-prop-object',
    'react/void-dom-elements-no-children',
    'jsx-a11y/alt-text',
    'jsx-a11y/anchor-ambiguous-text',
    'jsx-a11y/anchor-has-content',
    'jsx-a11y/anchor-is-valid',
    'jsx-a11y/aria-activedescendant-has-tabindex',
    'jsx-a11y/aria-props',
    'jsx-a11y/aria-proptypes',
    'jsx-a11y/aria-role',
    'jsx-a11y/aria-unsupported-elements',
    'jsx-a11y/autocomplete-valid',
    'jsx-a11y/click-events-have-key-events',
    'jsx-a11y/control-has-associated-label',
    'jsx-a11y/heading-has-content',
    'jsx-a11y/html-has-lang',
    'jsx-a11y/iframe-has-title',
    'jsx-a11y/img-redundant-alt',
    'jsx-a11y/interactive-supports-focus',
    'jsx-a11y/label-has-associated-control',
    'jsx-a11y/lang',
    'jsx-a11y/media-has-caption',
    'jsx-a11y/mouse-events-have-key-events',
    'jsx-a11y/no-access-key',
    'jsx-a11y/no-aria-hidden-on-focusable',
    'jsx-a11y/no-autofocus',
    'jsx-a11y/no-distracting-elements',
    'jsx-a11y/no-interactive-element-to-noninteractive-role',
    'jsx-a11y/no-noninteractive-element-interactions',
    'jsx-a11y/no-noninteractive-element-to-interactive-role',
    'jsx-a11y/no-noninteractive-tabindex',
    'jsx-a11y/no-redundant-roles',
    'jsx-a11y/no-static-element-interactions',
    'jsx-a11y/prefer-tag-over-role',
    'jsx-a11y/role-has-required-aria-props',
    'jsx-a11y/role-supports-aria-props',
    'jsx-a11y/scope',
    'jsx-a11y/tabindex-no-positive',
  ]),
);

const eslintRules = [
  ...new Set([
    'react/boolean-prop-naming',
    'react/button-has-type',
    'react/default-props-match-prop-types',
    'react/destructuring-assignment',
    'react/display-name',
    'react/forbid-component-props',
    'react/forbid-elements',
    'react/forbid-foreign-prop-types',
    'react/function-component-definition',
    'react/hook-use-state',
    'react/iframe-missing-sandbox',
    'react/jsx-boolean-value',
    'react/jsx-child-element-spacing',
    'react/jsx-closing-bracket-location',
    'react/jsx-closing-tag-location',
    'react/jsx-curly-brace-presence',
    'react/jsx-curly-newline',
    'react/jsx-curly-spacing',
    'react/jsx-equals-spacing',
    'react/jsx-filename-extension',
    'react/jsx-first-prop-new-line',
    'react/jsx-fragments',
    'react/jsx-handler-names',
    'react/jsx-indent',
    'react/jsx-indent-props',
    'react/jsx-key',
    'react/jsx-max-props-per-line',
    'react/jsx-no-bind',
    'react/jsx-no-comment-textnodes',
    'react/jsx-no-constructed-context-values',
    'react/jsx-no-duplicate-props',
    'react/jsx-no-leaked-render',
    'react/jsx-no-script-url',
    'react/jsx-no-target-blank',
    'react/jsx-no-undef',
    'react/jsx-no-useless-fragment',
    'react/jsx-one-expression-per-line',
    'react/jsx-pascal-case',
    'react/jsx-props-no-multi-spaces',
    'react/jsx-props-no-spreading',
    'react/jsx-sort-props',
    'react/jsx-tag-spacing',
    'react/jsx-uses-react',
    'react/jsx-uses-vars',
    'react/jsx-wrap-multilines',
    'react/no-access-state-in-setstate',
    'react/no-array-index-key',
    'react/no-arrow-function-lifecycle',
    'react/no-children-prop',
    'react/no-danger',
    'react/no-danger-with-children',
    'react/no-deprecated',
    'react/no-did-mount-set-state',
    'react/no-did-update-set-state',
    'react/no-direct-mutation-state',
    'react/no-find-dom-node',
    'react/no-invalid-html-attribute',
    'react/no-is-mounted',
    'react/no-namespace',
    'react/no-redundant-should-component-update',
    'react/no-render-return-value',
    'react/no-string-refs',
    'react/no-this-in-sfc',
    'react/no-typos',
    'react/no-unescaped-entities',
    'react/no-unknown-property',
    'react/no-unsafe',
    'react/no-unstable-nested-components',
    'react/no-unused-prop-types',
    'react/no-unused-state',
    'react/no-will-update-set-state',
    'react/prefer-es6-class',
    'react/prefer-exact-props',
    'react/prefer-stateless-function',
    'react/prop-types',
    'react/react-in-jsx-scope',
    'react/require-default-props',
    'react/require-render-return',
    'react/self-closing-comp',
    'react/sort-comp',
    'react/state-in-constructor',
    'react/static-property-placement',
    'react/style-prop-object',
    'react/void-dom-elements-no-children',
    'react-hooks/component-hook-factories',
    'react-hooks/config',
    'react-hooks/error-boundaries',
    'react-hooks/exhaustive-deps',
    'react-hooks/gating',
    'react-hooks/globals',
    'react-hooks/immutability',
    'react-hooks/incompatible-library',
    'react-hooks/preserve-manual-memoization',
    'react-hooks/purity',
    'react-hooks/refs',
    'react-hooks/rules-of-hooks',
    'react-hooks/set-state-in-effect',
    'react-hooks/set-state-in-render',
    'react-hooks/static-components',
    'react-hooks/unsupported-syntax',
    'react-hooks/use-memo',
    'jsx-a11y/alt-text',
    'jsx-a11y/anchor-ambiguous-text',
    'jsx-a11y/anchor-has-content',
    'jsx-a11y/anchor-is-valid',
    'jsx-a11y/aria-activedescendant-has-tabindex',
    'jsx-a11y/aria-props',
    'jsx-a11y/aria-proptypes',
    'jsx-a11y/aria-role',
    'jsx-a11y/aria-unsupported-elements',
    'jsx-a11y/autocomplete-valid',
    'jsx-a11y/click-events-have-key-events',
    'jsx-a11y/control-has-associated-label',
    'jsx-a11y/heading-has-content',
    'jsx-a11y/html-has-lang',
    'jsx-a11y/iframe-has-title',
    'jsx-a11y/img-redundant-alt',
    'jsx-a11y/interactive-supports-focus',
    'jsx-a11y/label-has-associated-control',
    'jsx-a11y/label-has-for',
    'jsx-a11y/lang',
    'jsx-a11y/media-has-caption',
    'jsx-a11y/mouse-events-have-key-events',
    'jsx-a11y/no-access-key',
    'jsx-a11y/no-autofocus',
    'jsx-a11y/no-distracting-elements',
    'jsx-a11y/no-interactive-element-to-noninteractive-role',
    'jsx-a11y/no-noninteractive-element-interactions',
    'jsx-a11y/no-noninteractive-element-to-interactive-role',
    'jsx-a11y/no-noninteractive-tabindex',
    'jsx-a11y/no-redundant-roles',
    'jsx-a11y/no-static-element-interactions',
    'jsx-a11y/role-has-required-aria-props',
    'jsx-a11y/role-supports-aria-props',
    'jsx-a11y/scope',
    'jsx-a11y/tabindex-no-positive',
  ]),
];

const diff = eslintRules.filter((x) => !oxlintRules.has(x));
console.info(diff, diff.length);

// eslint-plugin-react は後方互換性を保つために、createComponent や Class Component に関する古いルールを残している。
// 一方 oxlint は Hooks 以降のルールに絞っているため、必然的にルール差分は多くなるが、これは意図した結果である。
// eslint-plugin-react-hooks は、React が RSC を提供したことを受けて大量にルールを追加しており、 oxlint はまだそれに追従できていないことが分かる。
// ただし、それらのルールはいずれサポートされると期待できるのと、直近はそこまで重要ではないため、これも懸念材料とはならない。

// [
//   'react/boolean-prop-naming',
//   'react/default-props-match-prop-types',
//   'react/destructuring-assignment',
//   'react/forbid-foreign-prop-types',
//   'react/function-component-definition',
//   'react/jsx-child-element-spacing',
//   'react/jsx-closing-bracket-location',
//   'react/jsx-closing-tag-location',
//   'react/jsx-curly-newline',
//   'react/jsx-curly-spacing',
//   'react/jsx-equals-spacing',
//   'react/jsx-first-prop-new-line',
//   'react/jsx-indent',
//   'react/jsx-indent-props',
//   'react/jsx-max-props-per-line',
//   'react/jsx-no-bind',
//   'react/jsx-no-leaked-render',
//   'react/jsx-one-expression-per-line',
//   'react/jsx-props-no-multi-spaces',
//   'react/jsx-sort-props',
//   'react/jsx-tag-spacing',
//   'react/jsx-uses-react',
//   'react/jsx-uses-vars',
//   'react/jsx-wrap-multilines',
//   'react/no-access-state-in-setstate',
//   'react/no-arrow-function-lifecycle',
//   'react/no-deprecated',
//   'react/no-invalid-html-attribute',
//   'react/no-typos',
//   'react/no-unused-prop-types',
//   'react/no-unused-state',
//   'react/prefer-exact-props',
//   'react/prefer-stateless-function',
//   'react/prop-types',
//   'react/require-default-props',
//   'react/require-render-return',
//   'react/sort-comp',
//   'react/static-property-placement',
//   'react-hooks/component-hook-factories',
//   'react-hooks/config',
//   'react-hooks/error-boundaries',
//   'react-hooks/gating',
//   'react-hooks/globals',
//   'react-hooks/immutability',
//   'react-hooks/incompatible-library',
//   'react-hooks/preserve-manual-memoization',
//   'react-hooks/purity',
//   'react-hooks/refs',
//   'react-hooks/set-state-in-effect',
//   'react-hooks/set-state-in-render',
//   'react-hooks/static-components',
//   'react-hooks/unsupported-syntax',
//   'react-hooks/use-memo',
//   'jsx-a11y/label-has-for'
// ] 54
