name: Check oxlint-config

on:
  pull_request:
    branches:
      - '*'
    paths:
      - 'packages/oxlint-config/**'

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: packages/oxlint-config
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    strategy:
      fail-fast: false
      matrix:
        task:
          - lint
          - test:snapshot
          - build
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Initialize
        uses: ./.github/actions/restore-node
        with:
          working_directory: ${{ env.WORKING_DIRECTORY }}

      - name: Run ${{ matrix.task }}
        run: pnpm ${{ matrix.task }}
